webtalk_init -webtalk_dir C:\\Users\\zhang\\lab\\final_lab\\final_lab.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ÐÇÆÚÎå ÁùÔÂ 26 00:19:46 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "207600880_1777491182_0_870" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "o0lrjqmshd27oahfnlr30gnnu4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.2_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2494 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1435246447523" -context "sdk\\\\bsp/1435246447523"
webtalk_add_data -client sdk -key hwid -value "1435245246285" -context "sdk\\\\bsp/1435246447523"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1435246447523"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1435246447523"
webtalk_add_data -client sdk -key uid -value "1435246510586" -context "sdk\\\\application/1435246510586"
webtalk_add_data -client sdk -key hwid -value "1435245246285" -context "sdk\\\\application/1435246510586"
webtalk_add_data -client sdk -key bspid -value "1435246447523" -context "sdk\\\\application/1435246510586"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1435246510586"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1435246510586"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1435246510586"
webtalk_transmit -clientid 462685807 -regid "207600880_1777491182_0_870" -xml C:\\Users\\zhang\\lab\\final_lab\\final_lab.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\zhang\\lab\\final_lab\\final_lab.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\zhang\\lab\\final_lab\\final_lab.sdk\\webtalk\\sdk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
